name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache SonarCloud
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  owasp-zap:
    name: OWASP ZAP Dynamic Analysis
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start application
        run: |
          docker-compose up -d

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.0.18
        with:
          target: 'http://localhost:8080'
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}

  snyk:
    name: Snyk Source Component Scanning
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
